CREATE DATABASE appemprestimo;

use appemprestimo;

CREATE TABLE SOLICITANTE (
	CODIGO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(85),
	CPF VARCHAR(14)
);

select * from solicitante;


CREATE TABLE PRODUTO (
	CODIGO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TITULO VARCHAR(120),
	QTDEXEMPLARES INT,
	VALORUNITARIO DOUBLE
);


INSERT INTO PRODUTO (CODIGO, TITULO, QTDEXEMPLARES, VALORUNITARIO) VALUES (null, 'Timoneiras', 5, 10);
INSERT INTO PRODUTO (CODIGO, TITULO, QTDEXEMPLARES, VALORUNITARIO) VALUES (null, 'Gatilhos Mentais', 3, 32);
INSERT INTO PRODUTO (CODIGO, TITULO, QTDEXEMPLARES, VALORUNITARIO) VALUES (null, 'Clean Code', 10, 55);

CREATE TABLE EMPRESTIMO (
	NUMERO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DATAEMPRESTIMO date,
	DATADEVOLUCAO date,
	SOLICITANTE_COD INT,
	foreign key (SOLICITANTE_COD) references SOLICITANTE(CODIGO)
);

CREATE TABLE ITENS_EMPRESTIMO (
	CODIGO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	EMPRESTIMO_COD INT,
	PRODUTO_COD INT,
	foreign key (EMPRESTIMO_COD) references EMPRESTIMO(NUMERO),
	foreign key (PRODUTO_COD) references PRODUTO(CODIGO)
);

INSERT INTO EMPRESTIMO (NUMERO, DATAEMPRESTIMO, DATADEVOLUCAO, SOLICITANTE_COD) VALUES (null, '2022-10-29 17:11:00.000', '2022-11-30 17:11:00.000', 5);

INSERT INTO ITENS_EMPRESTIMO (CODIGO, EMPRESTIMO_COD, PRODUTO_COD) VALUES (null, 1, 1);
INSERT INTO ITENS_EMPRESTIMO (CODIGO, EMPRESTIMO_COD, PRODUTO_COD) VALUES (null, 1, 2);
INSERT INTO ITENS_EMPRESTIMO (CODIGO, EMPRESTIMO_COD, PRODUTO_COD) VALUES (null, 1, 3);


SELECT E.NUMERO, E.DATADEVOLUCAO, S.NOME, P.TITULO, P.VALORUNITARIO
FROM EMPRESTIMO E
JOIN SOLICITANTE S
JOIN ITENS_EMPRESTIMO IE
JOIN PRODUTO P
ON E.SOLICITANTE_COD = S.CODIGO
AND E.NUMERO = IE.EMPRESTIMO_COD
AND P.CODIGO = IE.PRODUTO_COD;












